version: "3.8"

services:
  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "7017:27017"
    volumes:
      - mongodb_data:/data/db

  # Zookeeper Ã¨ necessario per gestire lo stato di Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Il Broker Kafka
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  app:
    image: my-test:v1
    restart: on-failure
    depends_on:
      - mongo_db
      - kafka
    ports:
      - "6868:8080"
    environment:
      # Aggiungiamo la configurazione Kafka a Spring
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://root:123456@mongo_db:27017/bezkoder_db?authSource=admin",
          "spring.kafka.bootstrap-servers" : "kafka:29092",
          "spring.kafka.consumer.group-id" : "my-group"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  producer-app:
    image: my-producer-app:v1
    ports:
      - "8081:8081"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SERVER_PORT=8081
    depends_on:
      - kafka






volumes:
  mongodb_data: